# Assets
ASSETS = ["SPY", "QQQ", "AAPL", "NVDA", "TSLA", "MSFT", "META", "AMZN"]

# Market hours ET
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MIN = 30
OR_LOCK_HOUR = 10
OR_LOCK_MIN = 0
OR_DURATION_MIN = 30
CUTOFF_HOUR = 15
CUTOFF_MIN = 30
MARKET_CLOSE_HOUR = 16

# Signal detection
PROXIMITY_PCT = 0.005
CONFLUENCE_DIST_PCT = 0.003
MIN_LEVEL_SCORE = 6
MAX_RETEST_CANDLES = 15
RETEST_PROXIMITY = 0.003

# Volume thresholds
BREAKOUT_VOL_MIN = 1.3
REJECTION_VOL_MIN = 1.2
RETEST_VOL_MIN = 0.8
STOP_HUNT_VOL_MIN = 1.0

# Timeouts
RETEST_TIMEOUT_SEC = 900
STOPHUNT_CONFIRM_SEC = 90
REJECTION_CONFIRM_SEC = 120

# Cooldowns
GLOBAL_PAUSE_SEC = 90
ASSET_COOLDOWN_SEC = 300
LEVEL_LOCK_DAILY = True

# Risk
MIN_RR = 1.5
MAX_SIGNALS_PER_ASSET = 6

# VIX thresholds
VIX_HARD_BLOCK = 35
VIX_REDUCE_HALF = 25
VIX_REDUCE_QUARTER = 30
VIX_SPREADS_ONLY = 30

# Level scores
SCORE_52W = 10
SCORE_MONTHLY = 9
SCORE_WEEKLY = 8
SCORE_PDH_PDL = 8
SCORE_PDC = 7
SCORE_ORH_ORL = 7
SCORE_POC = 6
SCORE_VAH_VAL = 6
SCORE_HVN = 5
SCORE_PMH_PML = 5
SCORE_VWAP = 4
SCORE_ROUND_10 = 4
SCORE_ROUND_5 = 3
SCORE_ZONE_STRONG = 9
SCORE_ZONE_MEDIUM = 8
SCORE_ZONE_WEAK = 7
CONFLUENCE_BOOST = 2

# Data
DAILY_BARS_HISTORY = 252
ZONE_LOOKBACK_DAYS = 60
ZONE_SWING_BARS = 5
ZONE_MIN_TESTS = 2
ZONE_CLUSTER_PCT = 0.01
YFINANCE_STAGGER_SEC = 0.5

# Data health & validation
VALIDATE_INTERVAL_SEC = 300       # yfinance validation every 5 min
BACKFILL_MAX_GAP_SEC = 600        # max gap to backfill (10 min)
HEALTH_STALE_SEC = 30             # STALE after 30s no ticks
HEALTH_DEGRADED_BARS = 3          # DEGRADED if 3+ bars backfilled
VOL_DIVERGENCE_THRESHOLD = 0.20   # 20% volume divergence = warning
PRICE_DIVERGENCE_THRESHOLD = 0.001  # 0.1% price divergence = warning
YF_MAX_CONCURRENT = 2             # max concurrent yfinance HTTP calls
YF_DELAY_MINUTES = 15             # yfinance data delay
YF_VALIDATE_WINDOW = 5            # validate 5-min window (T-20 to T-15)
HEARTBEAT_SEC = 1                 # bar close heartbeat interval

# GPT
GPT_MODEL = "gpt-5.4"
GPT_MAX_TOOL_CALLS = 10
